<?='<?php'?>

/**
 * Generated by pharext v<?=pharext\VERSION?> at <?=date("Y-m-d H:i:i T")?>.
 */
namespace pharext;

return function(Installer $installer) {
	$args = $installer->getArgs();
	<?php foreach ($configure as $cfg) : ?>
	
	$args->compile([[
		null, 
		"<?=$cfg["name"]?>", 
		"<?=ucfirst($cfg["prompt"])?>", 
		CliArgs::OPTARG,
		<?php if (strlen($cfg["default"])) : ?>
		"<?=$cfg["default"]?>"
		<?php else : ?>
		NULL
		<?php endif; ?>
		
	]]);
	<?php endforeach; ?>
	
	return function(Installer $installer) {
		$args = $installer->getArgs();
		<?php foreach ($configure as $cfg) : ?>
		
		if (isset($args["<?=$cfg["name"]?>"])) {
			$args->configure = "--<?=$cfg["name"]?>=".$args["<?=$cfg["name"]?>"];
		}
		<?php endforeach; ?>
		
	};
};
